---
title: "Lesson 1.4"
subtitle: "Bivariate Transformation"
format: pdf
editor: visual
font: 12px
---
\setcounter{page}{14}

## Introduction

So far in this module, we have talked about transformations involving a single random variable $Y$. It is sometimes of interest to consider **bivariate transformation** such as 

$$
\begin{aligned}
U_1 &= g_1(Y_1, Y_2) \\
U_2 &= g_1(Y_1, Y_2)
\end{aligned}
$$

To discuss such transformations, we will assume that $Y_1$ and $Y_2$ are jointly **continuous** random variables. Furthermore, for the following methods to apply, the transformation needs to be **one-to-one**. We start with the joint distribution of $\mathbf{Y} = (Y_1, Y_2)$. Our first goal is to find the joint distribution of  $\mathbf{U} = (U_1, U_2)$.

## Bivariate Transformation

Suppose that $\mathbf{Y} = (Y_1, Y_2)$ is a continuous random vector with joint PDF $f_{Y_1, Y_2}(y_1, y_2)$. Let $g: \mathbb{R}^2 \rightarrow  \mathbb{R}^2$ be a continuous one-to-one vector-valued mapping from $R_{Y_1,Y_2}$ to $R_{U_1,U_2}$, where $U_1 = g_1(Y_1,Y_2)$ and $U_2 = g_2(Y_1,Y_2)$, and where $R_{Y_1,Y_2}$ and $R_{U_1,U_2}$ denote two-dimensional supports of $\mathbf{Y} = (Y_1, Y_2)$ and $\mathbf{U} = (U_1, U_2)$, respectively.

If $g_1^{-1}(u_1,u_2)$ and $g_2^{-1}(u_1,u_2)$ have continuous partial derivatives with respect to both $u_1$ and $u_2$ and the Jacobian, $J$, where "det" denote "determinant",

$$
J = det\begin{bmatrix} 
\frac{\partial g_1^{-1}(u_1,u_2)}{\partial u_1}  & \frac{\partial g_1^{-1}(u_1,u_2)}{\partial u_2}\\ 
\frac{\partial g_2^{-1}(u_1,u_2)}{\partial u_1}  & \frac{\partial g_2^{-1}(u_1,u_2)}{\partial u_2}
\end{bmatrix} \neq 0 
$$

then

$$
f_{U_1,U_2}(u_1,u_2) = \begin{cases}
f_{Y_1,Y_2}[g_1^{-1}(u_1,u_2), g_2^{-1}(u_1,u_2)]\times |J|, \,\, (u_1,u_2) \in R_{U_1,U_2} \\
0, \, \text{elsewhere}
\end{cases}
\tag{1}
$$

where $|J|$ denotes the avbsolute value of $J$.

\
To summarize, the steps involved in bivariate trabsformation are:

1. Find the joint distribution $f_{Y_1,Y_2}(y_1,y_2)$ of $Y_1$ and $Y_2$.

2. Find the $R_{U_1,U_2}$ the support of $\mathbf{U} = (U_1, U_2)$.

3. Find the inverse transformations $y_1 = g_1^{-1}(u_1,u_2)$ and $y_2 = g_2^{-1}(u_1,u_2)$.

4. Find the Jacobian, $J$, of the inverse transformation.

5. Use (1) to find $f_{U_1,U_2}(u_1,u_2)$ the joint distribution of $U_1$ and $U_2$. 

















